{{- if .Values.istio.enabled }}
  {{- if .Values.istio.authorizationPolicy.enabled }}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ .Values.name }}-authz
  namespace: {{ include "namespace" . }}
  labels: {{- include "webapp.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "webapp.selectorLabels" $ | nindent 6 }}
  action: {{ .Values.istio.authorizationPolicy.action | default "ALLOW" }}
  rules:
    {{- toYaml .Values.istio.authorizationPolicy.rules | nindent 4 }}
  {{- end }}
{{- end }}
