{{- if .Values.serviceAccount -}}
{{- $general := $.Values.serviceAccountGeneral -}}
{{- $serviceAccount := list -}}
{{- if kindIs "string" .Values.serviceAccount -}}
{{- $serviceAccount = fromYaml .Values.serviceAccount -}}
{{- else if kindIs "map" .Values.serviceAccount -}}
{{- $serviceAccount = .Values.serviceAccount -}}
{{- end -}}
{{- range $name, $val := $serviceAccount }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helpers.app.fullname" (dict "name" $name "context" $) }}
  namespace: {{ $.Release.Namespace | quote }}
  # labels: 
  # annotations:
{{- end }}
{{- end }}

