# Apply label "patch" if head matches one of "bugfix/*" or "hotfix/*"
patch:
  head: ["bugfix/*", "hotfix/*", "feature", "fix"]

# Apply label "minor" if head matches "feature/*"
minor:
  head: ["release/*"]

# Apply label "manor" if head matches "feature/*"
major:
  head: ["major/*", "breaking/*"]
