# Default values for australian-payments-plus.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# --name is the GitHub repository name of this application deployment
name: ""

# --nameOverride allows partial override of the name
nameOverride: {}

# --fullnameOverride allows full override of the name
fullnameOverride: {}

global:
  # --cluster sets the Cluster Name
  cluster: cluster.local
  # --env sets the Environment Name (dev, mng, prd)
  env: ""
  # --prometheus sets the Prometheus server URL
  prometheus:
    # --server sets prometheus endpoint
    server: ""
  # -- Network configuration
  network:
    # --domain sets the Default Domain
    domain: ""
  # --otel sets the endpoint for OpenTelemetry collector
  otel:
    endpoint: ""
    port: ""
    argument: "0.25"

# --commonLabels sets common labels for all resources
commonLabels: {}
# team_name: dev
# --restartPolicy is the object to specify the restart policy for the container
restartPolicy: Always
# --terminationGracePeriodSeconds is the number of seconds to wait before terminating a pod
terminationGracePeriodSeconds: 30
# --command is the object to specify the command to run in the container
command: []
# --args is the object to specify the arguments to run in the container
args: []

# --namespace configuration
namespace:
  # --Specifies whether the namespace is enabled
  enabled: false
  # --Labels to be added to the namespace
  labels: {}
  # --Annotations to be added to the namespace
  annotations: {}
  # --Example annotation to enable Jaeger tracing sidecar injection
  # sidecar.jaegertracing.io/inject: "true"

# --autoReloader enable auto reloader to restart the container when the configMap is updated
autoReloader: true

# --deployment Disabled Deployment
deployment:
  # --enabled is the flag to sinalize this funcionality is enabled
  enabled: true
  # --strategyType is the type of deployment strategy to use
  strategyType: RollingUpdate
  # --annotations to be added to the deployment
  annotations: {}
  # --labels to be added to the deployment
  labels: {}

# --service
service:
  # --service.enabled to enable and disable the creation of service
  enabled: true
  # --Service An abstract way to expose an application running on a set of Pods as a network service.
  type: ClusterIP
  # --service.port Define the Service Port
  port:
    # --Name of the port, used for service discovery
    name: tcp-node
    # --Port is the port your application runs under
    port: 80
    # --targetPort is the port your application runs under
    targetPort: 8080
  # --Annotations to add to the service
  annotations: {}
  # --Labels to add to the service
  labels: {}
  # --service.externalDns to enable and disable the creation of external DNS
  externalDns:
    # --Enable or disable external DNS for the service
    enabled: false
  # --The port to expose on each node in a cluster, only used if type is NodePort or LoadBalancer
  nodePort: {}

# --istio Set default Istio
istio:
  # enable istio-injection label on namespace
  enabled: true
  # --istio.virtualServices Set Istio virtualServices parameters
  virtualServices:
    # --istio.virtualServices.enable Set Istio virtualServices enabled
    enabled: true
    public: false
    custom:
      hosts: []
  # --PeerAuthentication defines how traffic will be tunneled (or not) to the sidecar.
  peerAuthentication:
    # --enable peerAuthentication
    enabled: true
    # --set peerAuthentication mode, values (UNSET, DISABLE, PERMISSIVE, STRICT)
    mode: PERMISSIVE
  # --gateways set default gateway for virtual-service
  gateways: istio-ingress/istio-ingressgateway
  # --authorizationPolicy set default authorization policy
  authorizationPolicy:
    # --enable authorizationPolicy
    enabled: true
    # Optional, since default is ALLOW
    action: ALLOW
    # No rules means "ALLOW ALL" in Istio when action is ALLOW
    rules:
      - from:
          - source:
              namespaces: ["*"]

# --ServiceAccount A service account provides an identity for processes that run in a Pod, about more: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
serviceAccount:
  name: {}
  # --Specifies whether a service account should be created
  enabled: true
  # --Annotations to add to the service account
  annotations: {}
  # --serviceAccount.annotations Automont Service Account Token
  automountServiceAccountToken: true

# --replicaCount is used when autoscaling.enabled is false to set a manually number of pods
replicaCount: 1
# --autoscaling is the main object of autoscaling
autoscaling:
  # --enabled is the flag to sinalize this funcionality is enabled
  enabled: true
  # --minReplicas is the number of mim pods to be running
  minReplicas: 1
  # --maxReplicas is the number of maximum scaling pods
  maxReplicas: 2
  # --targetCPUUtilizationPercentage is the percentage of cpu when reached to scale new pods
  targetCPUUtilizationPercentage: 80
  # --targetMemoryUtilizationPercentage is the percentage of memoty when reached to scale new pods
  targetMemoryUtilizationPercentage: 80
  # --customRules is a place to customize your application autoscaler using the original API available at: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/
  customRules:
    []
    # - type: Resource
    #   resource:
    #     name: memory
    #     target:
    #       type: Utilization
    #       averageUtilization: 20

container:
  # --port is the port your application runs under
  port: 8080
  # --readOnlyRootFilesystem is the prop to setup the container root filesystem as read-only
  readOnlyRootFilesystem: true

  # --image is the object to specify the image to run in the deployment
image:
  # --repository: is the registry of your application ex:556684128444.dkr.ecr.us-east-1.amazonaws.com/YOU-APP-ECR-REPO-NAME
  # if empty this helm will auto generate the image using aws.registry/values.name:values.image.tag
  repository: ""
  # --pullPolicy is the prop to setup the behavior of pull police. options is: IfNotPresent \| allways
  pullPolicy: IfNotPresent
  # --especify the tag of your image to deploy
  tag: "latest"

# --imagePullSecrets secret used to download image on private container registry
imagePullSecrets:
  []
  # --imagePullSecrets.enabled create secret do pull docker images in private registrys
  # enabled: true
  # name: ghcr-secret

# --resources set deployment resources
resources:
  # --Resource requests are the minimum amount of CPU and memory that Kubernetes guarantees for the container
  requests:
    # --The amount of CPU requested for the container
    cpu: "50m"
    # --The amount of memory requested for the container
    memory: "64Mi"
  # --Resource limits are the maximum amount of CPU and memory that the container is allowed to use
  limits:
    # --The maximum amount of CPU the container can use
    cpu: "100m"
    # --The maximum amount of memory the container can use
    memory: "128Mi"

## Health Check
# --livenessProbe indicates whether the application is running and alive
livenessProbe:
  # --Specifies whether the liveness probe is enabled
  enabled: false
  # --The HTTP path to check for liveness
  path: /health-check/liveness
  # --The scheme to use for the liveness probe (e.g., HTTP or HTTPS)
  scheme: HTTP
  # --Specifies a command to run inside the container to determine liveness
  exec: {}
  # --Number of seconds after the container has started before liveness probes are initiated
  initialDelaySeconds: 10
  # --Number of seconds after which the liveness probe times out
  timeoutSeconds: 3
  # --How often (in seconds) to perform the liveness probe
  periodSeconds: 10
  # --Minimum consecutive failures for the probe to be considered failed after having succeeded
  failureThreshold: 3
  # --Minimum consecutive successes for the probe to be considered successful after having failed
  successThreshold: 1
  # --httpHeaders specifies custom headers to set in the request
  httpHeaders: []

# --readinessProbe indicates whether the application is ready to serve requests
readinessProbe:
  # --Specifies whether the readiness probe is enabled
  enabled: false
  # --The HTTP path to check for readiness
  path: /health-check/readiness
  # --The scheme to use for the readiness probe (e.g., HTTP or HTTPS)
  scheme: HTTP
  # --Specifies a command to run inside the container to determine readiness
  exec: {}
  # --Number of seconds after the container has started before readiness probes are initiated
  initialDelaySeconds: 10
  # --Number of seconds after which the readiness probe times out
  timeoutSeconds: 3
  # --How often (in seconds) to perform the readiness probe
  periodSeconds: 10
  # --Minimum consecutive failures for the probe to be considered failed after having succeeded
  failureThreshold: 3
  # --Minimum consecutive successes for the probe to be considered successful after having failed
  successThreshold: 1
  # --httpHeaders specifies custom headers to set in the request
  httpHeaders: []

# --nodeSelector allows you to constrain a Pod to only be able to run on particular node(s)
nodeSelector: {}

# --affinity allows you to define rules for pod scheduling based on node labels
affinity: {}

# --tolerations allows the pods to schedule onto nodes with taints
tolerations: []

# --topologySpreadConstraints allows you to constrain the pods to run on nodes with a certain topology
topologySpreadConstraints:
  # --topologySpreadConstraints.enabled specifies whether topology spread constraints should be applied
  enabled: true
  # --topologySpreadConstraints.maxSkew specifies the maximum skew allowed among the topologies
  maxSkew: 1
  # --topologySpreadConstraints.topologyKey specifies the key of the topology
  topologyKey: "topology.kubernetes.io/zone"
  # --topologySpreadConstraints.whenUnsatisfiable specifies the action to take when a constraint is not satisfied
  whenUnsatisfiable: "ScheduleAnyway"

# --podAnnotations adds custom annotations to the pod
podAnnotations: {}

# --A security context defines privilege and access control settings for a Pod or Container. About more: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
podSecurityContext:
  {}
  # --fsGroup: 2000

envs:
  []
  # examples:
  # please note that when the value is a number, you must quote the value to cast to string!
  # - name: ENVIROMENT
  #   value: dev
  # - name: ENVIROMENT1
  #   value: true

envFrom:
  []
  # examples:
  # please note that when the value is a number, you must quote the value to cast to string!
  # - configMapRef
  #     name: postgres-configs

# --volumes specifies pod volumes
volumes:
  []
  # - name: sensitive-config
  #   secret:
  #     secretName: app-secrets

# --volumeMounts specifies where Kubernetes will mount Pod volumes
volumeMounts:
  []
  # - name: sensitive-config
  #   mountPath: /sensitive-config/
  #   readOnly: true

# ExternalSecrets configuration
externalSecrets:
  # -- If enabled, ExternalSecret resources will be created to sync secrets from external sources (e.g., Vault).
  enabled: false
  # -- The time interval at which secrets are refreshed from the external source (e.g., Vault).
  # Default value is "30s", meaning secrets will be refreshed every 30 seconds.
  refreshInterval: "30s"
  secretStoreRef:
    # -- The kind of SecretStore used to fetch secrets.
    # By default, this is set to "ClusterSecretStore" to allow cluster-wide secret management.
    kind: ClusterSecretStore
    # -- The name of the SecretStore backend. For Vault, this typically refers to the Vault connection (e.g., "vault-backend").
    name: vault-backend
  target:
    # -- The creation policy for the target Kubernetes Secret.
    # "Owner" means ExternalSecret manages the lifecycle of the created secret, deleting it when ExternalSecret is deleted.
    creationPolicy: Owner
  # -- List of secrets to be synced from the external source (e.g., Vault).
  # Add secrets here, where each secretKey in Kubernetes will map to a corresponding key in the external store.
  secrets: []
