{{- if .Values.istio.enabled }}
{{- if .Values.istio.virtualServices.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.name }}
  namespace: {{ include "namespace" . }}
  annotations:
    {{- if .Values.istio.virtualServices.public }}
    link.argocd.argoproj.io/external-link: https://{{ .Values.name }}.pub.{{ .Values.global.env }}.{{ .Values.global.network.domain }}
    {{- else }}
    link.argocd.argoproj.io/external-link: https://{{ .Values.name }}.pvt.{{ .Values.global.env }}.{{ .Values.global.network.domain }}
    {{- end }}
  labels:
    app: {{ .Values.name }}
    version: {{ .Values.image.tag | quote }}
    backstage.io/kubernetes-id: {{ .Values.name }}
spec:
  gateways:
    {{- if .Values.istio.virtualServices.public }}
    - istio-ingress/ingressgateway-pub
    {{- else }}
    - istio-ingress/ingressgateway-pvt
    {{- end }}
  hosts:
  {{- include "vs-hosts" . | indent 2 }}
  http:
  - name: {{ .Values.name }}
    route:
    - destination:
        host: {{ .Values.name }}.{{ include "namespace" . }}.svc.{{ .Values.global.cluster }}
        port:
          number: {{ .Values.service.port.port }}
  {{- end }}
{{- end }}
