# Default values for devxp-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# --name is the github repository name of this application deploy
name: "ci"
global: 
  env: dev
monitoring:
  serviceMonitor:
    enabled: true
    extraPort:
      enabled: true
actuator:
  enabled: false

externalSecrets:
  enabled: true
  secrets:
    - secretKey: FOO
      remoteRef:
        key: data/dev/ci
        property: FOO

consumers:
  terminationGracePeriodSeconds: 30
  list:
    - name: cron
      image:
        repository: XXXXXXXX.dkr.ecr.eu-central-2.amazonaws.com/ci-cron
        tag: 5d205f3
      resources:
        limits:
          cpu: 512m
          memory: 1G
        requests:
          cpu: 128m
          memory: 256Mi