# Default values for devxp-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# --name is the github repository name of this application deploy
name: "ci"
global: 
  env: dev
monitoring:
  serviceMonitor:
    enabled: true
    extraPort:
      enabled: true
actuator:
  enabled: false

# externalSecrets:
#   enabled: true
#   secrets:
#     - secretKey: API_KEY
#       remoteRef:
#         key: data/tha-dev-che-eks/managed-transaction-gateway
#         property: API_KEY