{{- if .Values.instrumentation.enabled }}
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: {{ .Values.name }}
  labels: {{ include "webapp.labels" . | nindent 4 }}
spec:
  env:
    - name: OTEL_METRICS_EXPORTER
      value: none
    - name: OTEL_LOGS_EXPORTER
      value: none
  exporter:
    endpoint: "{{ .Values.global.otel.endpoint }}:{{ .Values.global.otel.port }}"
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "{{ .Values.global.otel.argument }}"
  dotnet:
    env:
      - name: OTEL_SERVICE_NAME
        value: {{ .Values.name }}
      - name: OTEL_LOGS_EXPORTER
        value: otlp
  go:
    env:
      - name: OTEL_SERVICE_NAME
        value: {{ .Values.name }}
      - name: OTEL_LOGS_EXPORTER
        value: otlp
  java:
    env:
      - name: OTEL_SERVICE_NAME
        value: {{ .Values.name }}
      - name: OTEL_LOGS_EXPORTER
        value: otlp
  nodejs:
    env:
      - name: OTEL_SERVICE_NAME
        value: {{ .Values.name }}
      - name: OTEL_LOGS_EXPORTER
        value: otlp
  python:
    env:
      - name: OTEL_SERVICE_NAME
        value: {{ .Values.name }}
      - name: OTEL_LOGS_EXPORTER
        value: otlp
{{- end }}
