{{- if .Values.instrumentation.enabled }}
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: {{ .Values.name }}
  labels: {{ include "webapp.labels" . | nindent 4 }}
spec:
  exporter:
    endpoint: "{{ .Values.global.otel.endpoint }}:{{ .Values.global.otel.port }}"
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  dotnet:
    env:
      - name: OTEL_SERVICE_NAME
        value: {{ .Values.name }}
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: {{ .Values.global.otel.endpoint }}:4318
  go:
    env:
      - name: OTEL_SERVICE_NAME
        value: {{ .Values.name }}
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: {{ .Values.global.otel.endpoint }}:4317
  java:
    env:
      - name: OTEL_SERVICE_NAME
        value: {{ .Values.name }}
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: {{ .Values.global.otel.endpoint }}:4317
  nodejs:
    env:
      - name: OTEL_SERVICE_NAME
        value: {{ .Values.name }}
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: {{ .Values.global.otel.endpoint }}:4317
      - name: OTEL_LOG_LEVEL
        value: "info"
      - name: OTEL_LOGS_EXPORTER
        value: "otlp"
      - name: OTEL_TRACES_EXPORTER
        value: "otlp"
  python:
    env:
      - name: OTEL_SERVICE_NAME
        value: {{ .Values.name }}
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: {{ .Values.global.otel.endpoint }}:4318
{{- end }}
