{{- if not .Values.argoRollouts.enabled }} 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ include "namespace" . }}
  annotations: {{- include "all-deploy-annotations" . | nindent 4 }}
  labels: {{- include "webapp.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ default 1 .Values.replicaCount }}
  {{- end }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "webapp.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      annotations: {{- include "all-pod-annotations" . | nindent 8 }}
      labels: {{- include "webapp.labels" . | nindent 8 }}
    spec:
      imagePullSecrets: {{- toYaml (default list .Values.imagePullSecrets) | nindent 8 }}
      serviceAccountName: {{ .Values.name }}
      containers:
      - name: {{ .Values.name }}
        image: {{ include "image" . | quote }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env: {{- include "all-envs" . | nindent 12 }}
        envFrom: {{- include "all-EnvFrom" . | nindent 12 }}
        ports:
        - name: http
          containerPort: {{ .Values.container.port }}
        {{- if .Values.actuator.enabled }}
        - name: {{ .Values.actuator.port.name }}
          containerPort:  {{ .Values.actuator.port.targetPort }}
        {{- end }}
        {{- if .Values.livenessProbe.enabled }}
        {{- include "liveness-probe" ( dict "liveness" .Values.livenessProbe "port" .Values.container.port "actuator" .Values.actuator ) | indent 8 }}
        {{- end }}
        {{- if .Values.readinessProbe.enabled }}
        {{- include "readiness-probe" ( dict "readiness" .Values.readinessProbe "port" .Values.container.port "actuator" .Values.actuator ) | indent 8 }}
        {{- end }}
        resources: {{ toYaml .Values.resources | nindent 12 }}
        volumeMounts: {{ toYaml (default list .Values.volumeMounts)  | nindent 12 }}
      {{- if .Values.extraContainer.enabled }}
      - name: {{ .Values.extraContainer.name }}
        image: {{ .Values.extraContainer.image }}
        imagePullPolicy: {{ .Values.extraContainer.imagePullPolicy }}
        env: {{ toYaml .Values.extraContainer.env | nindent 12 }}
        ports:
        - name: {{ .Values.extraContainer.port.name }}
          containerPort: {{ .Values.extraContainer.port.containerPort }}
        resources: {{ toYaml .Values.extraContainer.resources | nindent 12 }}
        volumeMounts: {{ toYaml .Values.extraContainer.volumeMounts | nindent 12 }}
      {{- end }}        
      nodeSelector: {{ toYaml (default dict .Values.nodeSelector) | nindent 8 }}
      affinity: {{ toYaml (default dict .Values.affinity) | nindent 8 }}
      tolerations: {{ toYaml (default list .Values.tolerations)  | nindent 8 }}
      volumes: {{ toYaml (default list .Values.volumes)  | nindent 8 }}
  minReadySeconds: 30
{{- end }}