{{- if .Values.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default "ci" .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: ci
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: ci
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    backstage.io/kubernetes-id: ci
    cost-center: devops
    environment: ci
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    region: us-east-1
    team: devops
    version: {{ .Chart.AppVersion }}
  annotations:
    {{- if .Values.serviceAccount.irsa.enabled }}
    eks.amazonaws.com/role-arn: {{ printf "arn:aws:iam::%s:role/%s-%s-%s" .Values.aws.account .Values.global.org .Values.global.env .Values.name | quote }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
{{ toYaml . | indent 4 }}
    {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
