{{- if .Values.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.name }}
  namespace: {{ include "namespace" . }}
  labels: {{- include "webapp.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.serviceAccount.irsa.enabled }}
    eks.amazonaws.com/role-arn: {{ printf "arn:aws:iam::%s:role/%s-%s-%s" .Values.aws.account .Values.global.org .Values.global.env .Values.name | quote }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
      {{ toYaml . | indent 4 }}
    {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}

