---
{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "helm-ipfs-cluster.name" . }}-cluster
  labels:
    {{- include "helm-ipfs-cluster.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "helm-ipfs-cluster.selectorLabels" . | nindent 6 }}
      nodeType: cluster
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
{{- end }}