name: bump

on:
  pull_request:
    types: [closed]
    branches:
      - 'main'

jobs:
  bump-versions:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Git setup 🔧
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Get PR labels 🏷️
        id: pr-labels
        run: |
          LABELS=$(echo '${{ toJSON(github.event.pull_request.labels.*.name) }}' | jq -r '.[]' | tr '\n' ' ')
          echo "labels=$LABELS" >> "$GITHUB_OUTPUT"
          echo "Found labels: $LABELS"

      - name: Bump Version ✨
        run: |
          set -ex
          pip install --no-cache-dir bump2version
          python ./.github/callBump2version.py ${{ steps.pr-labels.outputs.labels }}

      - name: Push Results 🚀
        id: pushResults
        run: |
          if git merge-base --is-ancestor HEAD @{u} ; then
            echo "No push necessary"
          else
            echo "Version bumps happened. Pushing now..."
            git push
          fi